language: node_js
node_js:
  - '4.2.0'
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=test
  - PG_TEST=postgres://postgres@localhost:5432/foodujour_test
before_script:
  - npm install knex -g
  - psql -c 'create database foodujour_test;' -U postgres
  - knex migrate:latest
